// Active Plan (Model B, Phase 1) — the user's one committed, trackable 90-day plan.
// See docs/active-plan-design.md. Storage is per-user in `active_plans` (one active
// row); progress is deterministic (step completion + a snapshot delta vs the latest
// check-in). No LLM here — the plan is GENERATED by the existing action-plan edge fn
// and committed via startPlan(). In dev (USE_AI_MOCKS) it uses an in-memory store so
// the flow works on the sim before the migration is pushed.
import { withClient } from './supabaseClient';
import { TABLES } from './tables';
import { USE_AI_MOCKS } from '@/config/ai';
import type { ActionStep } from '@/types';
import type { FinalAnalysis } from '@shared/types';

export type StepStatus = 'pending' | 'done' | 'skipped';

export interface ActivePlanStep extends ActionStep {
  id: string;
  status: StepStatus;
  completed_at?: string | null;
}

export interface PlanStartMetrics {
  debtTotal: number;
  liquidSavings: number;
  monthlyIncome: number;
  monthlySavings: number;
  score: number;
}

export interface ActivePlan {
  id: string;
  source_analysis_id: string | null;
  started_at: string;
  horizon_days: number;
  status: 'active' | 'completed' | 'abandoned';
  version: number;
  overall_message: string | null;
  steps: ActivePlanStep[];
  start_metrics: PlanStartMetrics | null;
}

// ─── Deterministic progress (pure — no DB/LLM) ──────────────────────────────
export interface PlanProgress { done: number; total: number; pct: number; daysIn: number; daysLeft: number; }

export function planProgress(plan: ActivePlan, now: Date = new Date()): PlanProgress {
  const total = plan.steps.length;
  const done = plan.steps.filter((s) => s.status === 'done').length;
  const pct = total ? Math.round((done / total) * 100) : 0;
  const DAY = 24 * 60 * 60 * 1000;
  const daysIn = Math.max(0, Math.floor((now.getTime() - new Date(plan.started_at).getTime()) / DAY));
  const daysLeft = Math.max(0, plan.horizon_days - daysIn);
  return { done, total, pct, daysIn, daysLeft };
}

export interface PlanDelta { debtPaidDown: number; savingsGained: number; }

/** Improvement since the plan started, from the start snapshot vs the user's latest
 *  numbers (e.g. their most recent check-in). Clamped to non-negative. */
export function planDelta(
  start: PlanStartMetrics | null,
  latest: { debt?: number | null; savings?: number | null } | null,
): PlanDelta {
  if (!start) return { debtPaidDown: 0, savingsGained: 0 };
  const debtNow = latest?.debt ?? start.debtTotal;
  const savingsNow = latest?.savings ?? start.liquidSavings;
  return {
    debtPaidDown: Math.max(0, start.debtTotal - debtNow),
    savingsGained: Math.max(0, savingsNow - start.liquidSavings),
  };
}

// ─── Revision trigger gate (deterministic — no LLM) ─────────────────────────
// Decides whether a fresh analysis / check-in is a big enough change to bother
// revising the plan. This is the cost + relevance + trust keystone: a revise call
// only fires when the gate says yes, and NEVER when there's no committed plan.
export interface RevisionSnapshot { debtTotal?: number | null; liquidSavings?: number | null; monthlyIncome?: number | null; score?: number | null; }

const MATERIAL = { debt: 500, savings: 500, income: 200, score: 10 };

export function isMaterialChange(start: PlanStartMetrics | null, now: RevisionSnapshot | null): boolean {
  if (!start || !now) return false;
  const moved = (from: number, to?: number | null, by = 0) => to != null && Math.abs(from - to) >= by;
  if (start.debtTotal > 0 && now.debtTotal === 0) return true;            // debt fully paid off
  if (moved(start.debtTotal, now.debtTotal, MATERIAL.debt)) return true;
  if (moved(start.liquidSavings, now.liquidSavings, MATERIAL.savings)) return true;
  if (moved(start.monthlyIncome, now.monthlyIncome, MATERIAL.income)) return true;
  if (moved(start.score, now.score, MATERIAL.score)) return true;
  return false;
}

/** Should we revise the plan for this new snapshot? Returns false (no LLM call) when
 *  there's no committed plan — the app must NEVER auto-generate or revise without one. */
export function shouldRevisePlan(plan: ActivePlan | null, now: RevisionSnapshot | null): { revise: boolean; reason: string } {
  if (!plan) return { revise: false, reason: 'no active plan — never auto-generate or call revise' };
  if (plan.status !== 'active') return { revise: false, reason: `plan status is ${plan.status}` };
  if (!isMaterialChange(plan.start_metrics, now)) return { revise: false, reason: 'change below materiality threshold' };
  return { revise: true, reason: 'material change since the plan started' };
}

function metricsFromAnalysis(a: FinalAnalysis): PlanStartMetrics {
  return {
    debtTotal: a.debtTotal ?? 0,
    liquidSavings: a.liquidSavings?.value ?? 0,
    monthlyIncome: a.monthlyIncome?.value ?? 0,
    monthlySavings: a.monthlySavings ?? 0,
    score: a.score ?? 0,
  };
}

// ─── CRUD ───────────────────────────────────────────────────────────────────
// Dev-only in-memory store (resets on reload) so the flow works without the table.
let mockPlan: ActivePlan | null = null;

export async function getActivePlan(userId: string): Promise<ActivePlan | null> {
  if (USE_AI_MOCKS) return mockPlan;
  return withClient<ActivePlan | null>('fetch active plan', null, async (client) => {
    const { data, error } = await (client as any)
      .from(TABLES.active_plans)
      .select('*')
      .eq('user_id', userId)
      .eq('status', 'active')
      .maybeSingle();
    if (error) throw error;
    return (data as ActivePlan) ?? null;
  });
}

/** Commit a generated plan as the user's active plan (abandoning any prior one). */
export async function startPlan(
  userId: string,
  sourceAnalysisId: string | null,
  analysis: FinalAnalysis,
  steps: ActionStep[],
  overallMessage?: string,
): Promise<ActivePlan | null> {
  const planSteps: ActivePlanStep[] = steps.map((s, i) => ({
    ...s, id: `s${i}`, status: 'pending' as StepStatus, completed_at: null,
  }));
  const start_metrics = metricsFromAnalysis(analysis);

  if (USE_AI_MOCKS) {
    mockPlan = {
      id: 'mock-plan', source_analysis_id: sourceAnalysisId, started_at: new Date().toISOString(),
      horizon_days: 90, status: 'active', version: 1, overall_message: overallMessage ?? null,
      steps: planSteps, start_metrics,
    };
    return mockPlan;
  }
  return withClient<ActivePlan | null>('start plan', null, async (client) => {
    // Enforce one active plan per user — retire any existing active row first.
    await (client as any).from(TABLES.active_plans)
      .update({ status: 'abandoned', updated_at: new Date().toISOString() })
      .eq('user_id', userId).eq('status', 'active');
    const { data, error } = await (client as any).from(TABLES.active_plans).insert({
      user_id: userId,
      source_analysis_id: sourceAnalysisId,
      overall_message: overallMessage ?? null,
      steps: planSteps,
      start_metrics,
    }).select('*').single();
    if (error) throw error;
    return data as ActivePlan;
  });
}

/** Toggle a step's status (read-modify-write the steps array). Returns the updated plan. */
export async function setStepStatus(plan: ActivePlan, stepId: string, status: StepStatus): Promise<ActivePlan | null> {
  const steps = plan.steps.map((s) =>
    s.id === stepId ? { ...s, status, completed_at: status === 'done' ? new Date().toISOString() : null } : s,
  );
  if (USE_AI_MOCKS) { mockPlan = { ...plan, steps }; return mockPlan; }
  return withClient<ActivePlan | null>('update plan step', null, async (client) => {
    const { data, error } = await (client as any).from(TABLES.active_plans)
      .update({ steps, updated_at: new Date().toISOString() })
      .eq('id', plan.id).select('*').single();
    if (error) throw error;
    return data as ActivePlan;
  });
}

export async function abandonPlan(planId: string): Promise<boolean> {
  if (USE_AI_MOCKS) { mockPlan = null; return true; }
  return withClient('abandon plan', false, async (client) => {
    const { error } = await (client as any).from(TABLES.active_plans)
      .update({ status: 'abandoned', updated_at: new Date().toISOString() })
      .eq('id', planId);
    if (error) throw error;
    return true;
  });
}
