// Active Plan (Model B, Phase 1) — the user's one committed, trackable 90-day plan.
// See docs/active-plan-design.md. Storage is per-user in `active_plans` (one active
// row); progress is deterministic (step completion + a snapshot delta vs the latest
// check-in). No LLM here — the plan is GENERATED by the existing action-plan edge fn
// and committed via startPlan(). In dev (USE_AI_MOCKS) it uses an in-memory store so
// the flow works on the sim before the migration is pushed.
import { withClient } from './supabaseClient';
import { TABLES } from './tables';
import { USE_AI_MOCKS } from '@/config/ai';
import { revisePlanPatch } from './ai';
import { applyPatch } from '@shared/planRevision';
import type { ActionStep, RoastTone } from '@/types';
import type { FinalAnalysis } from '@shared/types';

export type StepStatus = 'pending' | 'done' | 'skipped';

export interface ActivePlanStep extends ActionStep {
  id: string;
  status: StepStatus;
  completed_at?: string | null;
}

export interface PlanStartMetrics {
  debtTotal: number;
  liquidSavings: number;
  monthlyIncome: number;
  monthlySavings: number;
  score: number;
}

export interface ActivePlan {
  id: string;
  source_analysis_id: string | null;
  started_at: string;
  horizon_days?: number;                              // fixed 90 (PLAN_HORIZON_DAYS) — derived, not stored
  status: 'active' | 'completed' | 'incomplete';      // schema-v2 status set (no 'abandoned')
  version?: number;                                   // in-memory revise counter — not persisted (dropped from action_plans)
  overall_message: string | null;
  steps: ActivePlanStep[];
  start_metrics: PlanStartMetrics | null;
  /** Metrics the plan currently REFLECTS (set at commit, re-set on revise). Staleness =
   *  the latest snapshot differs materially from this. Falls back to start_metrics.
   *  NOTE: prototype-only in dev/mock; prod persistence needs a DB column. */
  synced_metrics?: PlanStartMetrics | null;
}

// ─── Deterministic progress (pure — no DB/LLM) ──────────────────────────────
export const PLAN_HORIZON_DAYS = 90; // fixed plan window — ends_at = started_at + 90d (not stored as horizon_days)
export interface PlanProgress { done: number; total: number; pct: number; daysIn: number; daysLeft: number; }

export function planProgress(plan: ActivePlan, now: Date = new Date()): PlanProgress {
  const total = plan.steps.length;
  const done = plan.steps.filter((s) => s.status === 'done').length;
  const pct = total ? Math.round((done / total) * 100) : 0;
  const DAY = 24 * 60 * 60 * 1000;
  const daysIn = Math.max(0, Math.floor((now.getTime() - new Date(plan.started_at).getTime()) / DAY));
  const daysLeft = Math.max(0, PLAN_HORIZON_DAYS - daysIn);
  return { done, total, pct, daysIn, daysLeft };
}

export interface PlanDelta { debtPaidDown: number; savingsGained: number; }

/** Improvement since the plan started, from the start snapshot vs the user's latest
 *  numbers (e.g. their most recent check-in). Clamped to non-negative. */
export function planDelta(
  start: PlanStartMetrics | null,
  latest: { debt?: number | null; savings?: number | null } | null,
): PlanDelta {
  if (!start) return { debtPaidDown: 0, savingsGained: 0 };
  const debtNow = latest?.debt ?? start.debtTotal;
  const savingsNow = latest?.savings ?? start.liquidSavings;
  return {
    debtPaidDown: Math.max(0, start.debtTotal - debtNow),
    savingsGained: Math.max(0, savingsNow - start.liquidSavings),
  };
}

// ─── Revision trigger gate (deterministic — no LLM) ─────────────────────────
// Decides whether a fresh analysis / check-in is a big enough change to bother
// revising the plan. This is the cost + relevance + trust keystone: a revise call
// only fires when the gate says yes, and NEVER when there's no committed plan.
export interface RevisionSnapshot { debtTotal?: number | null; liquidSavings?: number | null; monthlyIncome?: number | null; score?: number | null; }

const MATERIAL = { debt: 500, savings: 500, income: 200, score: 10 };

export function isMaterialChange(start: PlanStartMetrics | null, now: RevisionSnapshot | null): boolean {
  if (!start || !now) return false;
  const moved = (from: number, to?: number | null, by = 0) => to != null && Math.abs(from - to) >= by;
  if (start.debtTotal > 0 && now.debtTotal === 0) return true;            // debt fully paid off
  if (moved(start.debtTotal, now.debtTotal, MATERIAL.debt)) return true;
  if (moved(start.liquidSavings, now.liquidSavings, MATERIAL.savings)) return true;
  if (moved(start.monthlyIncome, now.monthlyIncome, MATERIAL.income)) return true;
  if (moved(start.score, now.score, MATERIAL.score)) return true;
  return false;
}

/** Should we revise the plan for this new snapshot? Returns false (no LLM call) when
 *  there's no committed plan — the app must NEVER auto-generate or revise without one. */
export function shouldRevisePlan(plan: ActivePlan | null, now: RevisionSnapshot | null): { revise: boolean; reason: string } {
  if (!plan) return { revise: false, reason: 'no active plan — never auto-generate or call revise' };
  if (plan.status !== 'active') return { revise: false, reason: `plan status is ${plan.status}` };
  if (!isMaterialChange(plan.synced_metrics ?? plan.start_metrics, now)) return { revise: false, reason: 'change below materiality threshold' };
  return { revise: true, reason: 'material change since the plan started' };
}

function metricsFromAnalysis(a: FinalAnalysis): PlanStartMetrics {
  return {
    debtTotal: a.debtTotal ?? 0,
    liquidSavings: a.liquidSavings?.value ?? 0,
    monthlyIncome: a.monthlyIncome?.value ?? 0,
    monthlySavings: a.monthlySavings ?? 0,
    score: a.score ?? 0,
  };
}

// ─── CRUD ───────────────────────────────────────────────────────────────────
// Dev-only in-memory store (resets on reload) so the flow works without the table. Seeded with a
// sample ACTIVE plan so mock mode shows an existing tracked plan (not the "Create my plan" CTA).
let mockPlan: ActivePlan | null = {
  id: 'mock-active-plan',
  source_analysis_id: 'mock-1',
  started_at: '2026-06-01T00:00:00.000Z',
  horizon_days: 90,
  status: 'active',
  version: 1,
  overall_message: 'Three months to turn the leaks into a cushion — small, repeatable wins, not heroics.',
  steps: [
    { id: 's0', week: 'Week 1', title: 'Subscription purge', description: "Cancel every subscription you haven't used in 30 days. No mercy.", impact: 'Saves $80–200/mo', category: 'savings', confidence: 'high', status: 'done', completed_at: '2026-06-03T00:00:00.000Z' },
    { id: 's1', week: 'Week 2', title: 'Automate savings', description: 'Set a recurring transfer on payday so savings happen before you can spend.', impact: 'Builds the cushion', category: 'savings', confidence: 'high', status: 'done', completed_at: '2026-06-08T00:00:00.000Z' },
    { id: 's2', week: 'Weeks 3-4', title: 'Credit card minimum+', description: 'Pay minimums on all cards plus $50 extra on the highest-rate one.', impact: 'Cuts interest', category: 'debt', confidence: 'medium', status: 'pending', completed_at: null },
    { id: 's3', week: 'Weeks 5-8', title: 'Negotiate a bill', description: 'Call your internet, phone, or insurance and ask for a better rate.', impact: 'Saves $30–80/mo', category: 'savings', confidence: 'medium', status: 'pending', completed_at: null },
    { id: 's4', week: 'Weeks 9-12', title: '30-day review', description: 'Run a new roast and compare to your starting score.', impact: 'Accountability boost', category: 'mindset', confidence: 'high', status: 'pending', completed_at: null },
  ],
  start_metrics: { debtTotal: 7200, liquidSavings: 0, monthlyIncome: 4800, monthlySavings: -150, score: 37 },
  synced_metrics: { debtTotal: 7200, liquidSavings: 0, monthlyIncome: 4800, monthlySavings: -150, score: 37 },
};

export async function getActivePlan(userId: string): Promise<ActivePlan | null> {
  if (USE_AI_MOCKS) return mockPlan;
  return withClient<ActivePlan | null>('fetch active plan', null, async (client) => {
    const { data, error } = await (client as any)
      .from(TABLES.action_plans)
      .select('*')
      .eq('user_id', userId)
      .eq('status', 'active')
      .maybeSingle();
    if (error) throw error;
    return (data as ActivePlan) ?? null;
  });
}

/** Commit a generated plan as the user's active plan (abandoning any prior one). */
export async function startPlan(
  userId: string,
  sourceAnalysisId: string | null,
  analysis: FinalAnalysis,
  steps: ActionStep[],
  overallMessage?: string,
): Promise<ActivePlan | null> {
  const planSteps: ActivePlanStep[] = steps.map((s, i) => ({
    ...s, id: `s${i}`, status: 'pending' as StepStatus, completed_at: null,
  }));
  const start_metrics = metricsFromAnalysis(analysis);

  if (USE_AI_MOCKS) {
    mockPlan = {
      id: 'mock-plan', source_analysis_id: sourceAnalysisId, started_at: new Date().toISOString(),
      horizon_days: 90, status: 'active', version: 1, overall_message: overallMessage ?? null,
      steps: planSteps, start_metrics, synced_metrics: start_metrics,
    };
    return mockPlan;
  }
  return withClient<ActivePlan | null>('start plan', null, async (client) => {
    // Enforce one active plan per user — retire any existing active row first.
    await (client as any).from(TABLES.action_plans)
      .delete()
      .eq('user_id', userId).eq('status', 'active');
    const { data, error } = await (client as any).from(TABLES.action_plans).insert({
      user_id: userId,
      source_analysis_id: sourceAnalysisId,
      overall_message: overallMessage ?? null,
      steps: planSteps,
      start_metrics,
    }).select('*').single();
    if (error) throw error;
    return data as ActivePlan;
  });
}

/** Toggle a step's status (read-modify-write the steps array). Returns the updated plan. */
export async function setStepStatus(plan: ActivePlan, stepId: string, status: StepStatus): Promise<ActivePlan | null> {
  const steps = plan.steps.map((s) =>
    s.id === stepId ? { ...s, status, completed_at: status === 'done' ? new Date().toISOString() : null } : s,
  );
  if (USE_AI_MOCKS) { mockPlan = { ...plan, steps }; return mockPlan; }
  return withClient<ActivePlan | null>('update plan step', null, async (client) => {
    const { data, error } = await (client as any).from(TABLES.action_plans)
      .update({ steps, updated_at: new Date().toISOString() })
      .eq('id', plan.id).select('*').single();
    if (error) throw error;
    return data as ActivePlan;
  });
}

export async function abandonPlan(planId: string): Promise<boolean> {
  if (USE_AI_MOCKS) { mockPlan = null; return true; }
  return withClient('abandon plan', false, async (client) => {
    const { error } = await (client as any).from(TABLES.action_plans)
      .delete()
      .eq('id', planId);
    if (error) throw error;
    return true;
  });
}

export interface ReviseResult { revised: boolean; reason: string; plan: ActivePlan; }

/** Revise the active plan to a new snapshot. Gated by shouldRevisePlan (never fires
 *  without a committed plan or for an immaterial change), then: ask for a patch →
 *  apply deterministically (shared engine, snapshot reality-checked) → persist
 *  version+1. Fail-soft: any failure leaves the current plan untouched. */
export async function reviseActivePlan(
  plan: ActivePlan,
  change: string,
  snapshot: PlanStartMetrics,
  tone: RoastTone,
): Promise<ReviseResult> {
  const gate = shouldRevisePlan(plan, snapshot);
  if (!gate.revise) return { revised: false, reason: gate.reason, plan };

  const start = plan.start_metrics ?? snapshot;
  const patch = await revisePlanPatch(
    plan.steps as unknown as Parameters<typeof applyPatch>[0],
    change,
    { debtTotal: start.debtTotal, liquidSavings: start.liquidSavings, monthlyIncome: start.monthlyIncome, monthlySavings: start.monthlySavings, score: start.score },
    { debtTotal: snapshot.debtTotal, liquidSavings: snapshot.liquidSavings, monthlyIncome: snapshot.monthlyIncome, monthlySavings: snapshot.monthlySavings, score: snapshot.score },
    tone,
  );
  if (!patch) return { revised: false, reason: 'revision call failed — plan unchanged', plan };

  const { steps } = applyPatch(plan.steps as any, patch, { snapshot: { debtTotal: snapshot.debtTotal } });
  const revised: ActivePlan = {
    ...plan,
    steps: steps as unknown as ActivePlanStep[],
    // Keep the existing Big Picture when the patch message is empty (e.g. a no-op revision).
    overall_message: patch.overallMessage?.trim() ? patch.overallMessage : plan.overall_message,
    version: (plan.version ?? 0) + 1,
    synced_metrics: snapshot, // the plan now reflects this snapshot → status flips to "up to date"
  };

  if (USE_AI_MOCKS) { mockPlan = revised; return { revised: true, reason: gate.reason, plan: revised }; }
  const persisted = await withClient<ActivePlan | null>('revise plan', null, async (client) => {
    const { data, error } = await (client as any).from(TABLES.action_plans)
      .update({ steps: revised.steps, overall_message: revised.overall_message, updated_at: new Date().toISOString() })
      .eq('id', plan.id).select('*').single();
    if (error) throw error;
    return data as ActivePlan;
  });
  // Fail-soft: if the DB write failed, return the in-memory revised plan rather than corrupting state.
  return { revised: true, reason: gate.reason, plan: persisted ?? revised };
}
