import React from 'react';
import { View, Text, StyleSheet, ScrollView } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Colors, Typography, Spacing } from '@/theme/colors';
import ScreenBackground from '@/components/ScreenBackground';

export default function TermsOfServiceScreen() {
  const insets = useSafeAreaInsets();

  return (
    <View style={styles.container}>
      <ScreenBackground variant="info" />
      <ScrollView
        contentContainerStyle={[styles.scroll, { paddingBottom: insets.bottom + 40 }]}
        showsVerticalScrollIndicator={false}
      >
      <Text style={styles.lastUpdated}>Last Updated: May 2026</Text>

      <Text style={styles.paragraph}>
        By using Am I Broke? ("the App"), you agree to the following terms and conditions. Please
        read them carefully.
      </Text>

      <Text style={styles.heading}>1. Service Description</Text>
      <Text style={styles.paragraph}>
        Am I Broke? is an AI-powered financial entertainment and education tool. It provides
        directional financial insights based on information you voluntarily provide. The App is not a
        financial advisor, budgeting tool, or substitute for professional financial guidance.
      </Text>

      <Text style={styles.heading}>2. Not Financial Advice</Text>
      <Text style={styles.paragraph}>
        Am I Broke? is for educational and entertainment purposes only. It does not provide
        personalized financial advice, investment recommendations, or tax guidance. The output
        generated by the AI is based on limited information you provide and may not reflect your
        full financial situation. Always consult a licensed financial advisor for personalized
        guidance. Never make financial decisions solely based on the output of this App.
      </Text>

      <Text style={styles.heading}>3. User Responsibilities</Text>
      <Text style={styles.paragraph}>
        You agree to: provide accurate information when using the App (though we understand
        estimates are expected), use the App for lawful purposes only, not attempt to reverse
        engineer, copy, or exploit the App's code or design, and not use the App to harass, abuse,
        or harm others.
      </Text>

      <Text style={styles.heading}>4. Intellectual Property</Text>
      <Text style={styles.paragraph}>
        All content, design, code, and branding within Am I Broke? are owned by or licensed to us.
        You may not reproduce, distribute, or create derivative works without our express written
        permission. Your financial analysis results are yours to share as you wish.
      </Text>

      <Text style={styles.heading}>5. Limitation of Liability</Text>
      <Text style={styles.paragraph}>
        Am I Broke? and its creators shall not be liable for any direct, indirect, incidental,
        special, or consequential damages resulting from your use of the App. This includes
        financial losses, missed opportunities, or decisions made based on App output. The App is
        provided "as is" without warranty of any kind.
      </Text>

      <Text style={styles.heading}>6. Purchases and Refunds</Text>
      <Text style={styles.paragraph}>
        All purchases (Action Plans, Deep Dives) are one-time, non-refundable digital goods unless
        required otherwise by applicable law. If you experience a technical issue with your purchase,
        contact us at support@amibroke.app and we will address it promptly.
      </Text>

      <Text style={styles.heading}>7. Affiliate Disclosure</Text>
      <Text style={styles.paragraph}>
        The App may contain affiliate links to third-party products and services. We may earn a
        commission if you click these links and make a purchase. All affiliate links are clearly
        labeled as sponsored. These recommendations are based on your financial situation and are
        not paid placements.
      </Text>

      <Text style={styles.heading}>8. Termination</Text>
      <Text style={styles.paragraph}>
        We reserve the right to suspend or terminate access to the App for violations of these
        terms, fraudulent activity, or behavior that harms other users or the platform. You may
        discontinue use at any time by deleting your account and uninstalling the App.
      </Text>

      <Text style={styles.heading}>9. Changes to Terms</Text>
      <Text style={styles.paragraph}>
        We may update these terms from time to time. Continued use of the App after changes
        constitutes acceptance of the updated terms. We will notify users of material changes via
        the App or email.
      </Text>

      <Text style={styles.heading}>10. Governing Law</Text>
      <Text style={styles.paragraph}>
        These terms are governed by the laws of the State of Delaware, United States. Any disputes
        shall be resolved in the courts of Delaware.
      </Text>

      <Text style={styles.heading}>11. Contact</Text>
      <Text style={styles.paragraph}>
        For questions about these terms, contact us at legal@amibroke.app.
      </Text>
    </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  scroll: { paddingHorizontal: Spacing.xl, paddingTop: Spacing.lg },
  lastUpdated: {
    fontFamily: Typography.fonts.body,
    fontSize: Typography.footnote.fontSize,
    color: Colors.textMuted,
    marginBottom: Spacing.xl,
  },
  heading: {
    fontFamily: Typography.fonts.headingSemi,
    fontSize: 18,
    color: Colors.textPrimary,
    marginTop: Spacing.xxl,
    marginBottom: Spacing.sm,
  },
  paragraph: {
    fontFamily: Typography.fonts.body,
    fontSize: Typography.subhead.fontSize,
    color: Colors.textSecondary,
    lineHeight: 24,
    marginBottom: Spacing.md,
  },
});
